# Generated by Django 3.2.1 on 2021-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20210508_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminlogin',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
