# Generated by Django 3.2.1 on 2021-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_superadminlogin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dineintables',
            name='price',
        ),
        migrations.AddField(
            model_name='dineintables',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
