# Generated by Django 3.2.1 on 2021-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_rooms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
