# Generated by Django 3.2.1 on 2021-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_rooms_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingrooms',
            fields=[
                ('room_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('conference room', 'conference room'), ('ball room', 'ball room')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'meetingrooms',
            },
        ),
    ]
