# Generated by Django 3.2.1 on 2021-05-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_meetingrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('king guestroom', 'king guestroom'), ('king deluxe guestroom', 'king deluxe guestroom'), ('twin guestroom', 'twin guestroom')], max_length=50),
        ),
    ]
