# Generated by Django 3.2.1 on 2021-05-07 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookroommodel',
            fields=[
                ('email', models.CharField(default='x', max_length=40)),
                ('room_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1000.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'roombookings',
            },
        ),
        migrations.CreateModel(
            name='registrationmodel',
            fields=[
                ('firstname', models.CharField(default='tanuj', max_length=30)),
                ('lastname', models.CharField(default='tanuj', max_length=30)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usersdata',
            },
        ),
    ]
