# Generated by Django 3.2.1 on 2021-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroommodel',
            name='room_type',
            field=models.CharField(choices=[('king guestroom', 'king guestroom'), ('king deluxe guestroom', 'king deluxe guestroom'), ('twin guestroom', 'twin guestroom')], max_length=50),
        ),
    ]
