# Generated by Django 3.2.1 on 2021-05-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0004_alter_bookroommodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookroommodel',
            options={},
        ),
    ]
