# Generated by Django 3.2.1 on 2021-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdineinmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='x', max_length=40)),
                ('table_no', models.CharField(max_length=10)),
                ('price', models.FloatField(default=1000.0)),
                ('time', models.CharField(max_length=15)),
                ('space', models.CharField(default='xc', max_length=10)),
            ],
            options={
                'db_table': 'dineinbookings',
            },
        ),
    ]
