# Generated by Django 3.2.1 on 2021-05-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdineinmodel',
            name='price',
        ),
    ]
