# Generated by Django 3.2.1 on 2021-05-19 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_rooms_bookcount'),
        ('food', '0003_alter_bookdineinmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdineinmodel',
            name='table_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.dineintables'),
        ),
    ]
