# Generated by Django 3.2.1 on 2021-05-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_bookdineinmodel_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdineinmodel',
            name='table_no',
            field=models.CharField(max_length=10),
        ),
    ]
